# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'd09diary' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for d09diary
  pod 'sycohen2018', :path => "/Users/sycohen/code/SWIFT42/d08_clone/sycohen2018"

  
end
