print("Tacking a shuffled deck")
var shufflecards = Deck(shuffle: true)
print(shufflecards)

print("Tacking a sorted deck")
var sorted = Deck(shuffle: false)
print("\n\n taking a sorted deck")
print(sorted)
print("\ndrawing first two card of a sorted deck")
var draw = sorted.draw()
 draw = sorted.draw()
print(sorted)
print("**printing cards out:", sorted.outs)

var shuffledeck0 = Deck(shuffle: true)
print("\n\n taking a shuffledeck0 deck")
print(shuffledeck0)
print("\ndrawing first two card of a shuffledeck0 deck")
 draw = shuffledeck0.draw()
 draw = shuffledeck0.draw()
print(shuffledeck0)
print("printing cards out:", shuffledeck0.outs)

var shuffleddeck = Deck(shuffle: true)
print("\n\n taking a shuffled deck")
print(shuffleddeck)
print("\ndrawing all cards + 1 of a shuffled deck")
for _ in shuffleddeck.cards {
     draw = shuffleddeck.draw()
}
print(shuffleddeck)
print("printing cards out:", shuffleddeck.outs)

var shuffled2 = Deck(shuffle: true)
print("\n\n taking a new shuffled deck\n\n", shuffled2)
var handpicker = shuffled2.cards[1]
print("\n\nhandpicking a card from a shuffled deck", handpicker)
print("\ndrawing first two cards of a shuffled deck")
 draw = shuffled2.draw()
 draw = shuffled2.draw()
print("cards out:", shuffled2.outs)
print("cards discards:", shuffled2.discards)
print("\nfolding selected cards:", handpicker)
shuffled2.fold(c: handpicker)
print("cards out:", shuffled2.outs)
print("cards discards:", shuffled2.discards)
